### ISSUE TITLE
Animation delay[REQUEST]

### ISSUE THREAD

**Issue by ExceptedPrism3** [NikV2/LuckyPouchesAPI#2]
**Discord**
Prism3#0003

**What feature would you like to be added and why?**
When opening the pouches you directly see the money added to your balance, I thought it would be great to delay the money giving cmd, like for Legendary animation until the animation finishes and you see how much you gain then it's added to the money balance.
Idk it sounds great to me to keep the player in suspense for the amount that his getting xD

**Comment by NikV2** [comment]
I can't change that rn due to the current way the API works, I might change it in the future
